name: Fetch Image Digest from GCB
description: Use the GCB API to extract the Docker digest of a build completed for a given git SHA.
author: Craig Day

runs:
  using: node12
  main: action.js

inputs:
  build_url:
    description: The link to the GCB build so we can extract the build ID
    required: true
  target_image:
    description: The name of the image to find the digest for
    required: true

outputs:
  digest:
    description: The Docker digest for the image pulled from GCB
