name: Fetch Image Digest from GCB
description: Use the GCB API to extract the Docker digest of a build completed for a given git SHA.
author: Craig Day
branding:
  icon: code
  color: blue

runs:
  using: node12
  main: action.js

inputs:
  target_image:
    description: The name of the image to find the digest for
    required: true
  google_application_credentials:
    description: Service account credentials for your Google Cloud project
    required: true

outputs:
  digest:
    description: The Docker digest for the image pulled from GCB
  sha:
    description: The git sha associated with the image, if available
